// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "nav.gallery": "Gallery",
    "nav.about": "About",
    "nav.contact": "Contact",
    "hero.cta": "View Gallery",
    "about.title": "About",
    "contact.title": "Contact",
    "contact.send": "Send"
  };
export default messages;